apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: nextcloud-aio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - containerPort: {{ .targetPort }}
            {{- end }}
          volumeMounts:
            - name: config-data
              mountPath: /mnt/docker-aio-config
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
      volumes:
        - name: config-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket

