prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi   


grafana:
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 10Gi

